# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd47798fa29992ca81ea61049564a62ef9b93532ddf5378049269f2fb50f2baf1ee58ea3b74695160c5398c219dd984ce5f78f95cb4412a461893b834f000afb

test:
  secret_key_base: 29ad1c4afb21b90f6bef359ec503f88ec408605605ab787674fa601497a9170b9e810cd23272f2fdf73766ee501946a977c9b1e0e281dbb565755f9edf302896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
